### ISSUE TITLE
Rotate and flip the block and ask the server to return the flipped/rotated block.

### ISSUE THREAD

**Issue by turbodumba** [sopra-fs23-group-40/Client#11]
```[tasklist]
### Tasks
- [ ] https://github.com/sopra-fs23-group-40/Client/issues/42
- [ ] https://github.com/sopra-fs23-group-40/Client/issues/43
- [ ] https://github.com/sopra-fs23-group-40/Client/issues/44
```

**Comment by PaulPerpetual** [comment]
The way it was implemented in the final version is different then initially planned
