### ISSUE TITLE
Make it possible for a player to leave the Game

### ISSUE THREAD

**Issue by Karo2222** [sopra-fs23-group-40/Client#58]
```[tasklist]
### Tasks
- [x] Add REST endpoint /leaveGame to backend
- [x] Add method /leaveGame in gameService
- [x] Create PopUp when clicking on "Leave Game" on frontend => redirect once confirmed
```

**Comment by Karo2222** [comment]
Frontend:
https://github.com/sopra-fs23-group-40/Client/commit/74cf477c542b05e6c5400cd3b9a4171a8611065b
https://github.com/sopra-fs23-group-40/Client/commit/2adf324d507ec8e64fcfb864dafbae529f5d4f3d

Backend:
https://github.com/sopra-fs23-group-40/Server/commit/d7276520be3ecd646fdf62643ad2371e19857f86
